"""
Episodic memory — stores significant events, decisions, milestones.

Detection strategy: keyword matching instead of LLM classification.
The 1B model is too unreliable for Yes/No classification.
We detect milestone/event patterns in the user message.
The episode summary IS still generated by the LLM (that's a generation
task, not a classification task, so the model handles it well).
"""

import logging
import time
import uuid

from app.memory.maintenance import find_similar_memory
from app.core.config import MEMORY_SIMILARITY_THRESHOLD

logger = logging.getLogger(__name__)


# Keywords that strongly signal a significant event or milestone
_MILESTONE_SIGNALS = [
    "i finished",
    "i completed",
    "i built",
    "i created",
    "i deployed",
    "i launched",
    "i solved",
    "i fixed",
    "i learned",
    "i decided",
    "i figured out",
    "i managed to",
    "i succeeded",
    "i achieved",
    "i got",
    "we finished",
    "we completed",
    "we built",
    "we deployed",
    "just finished",
    "just completed",
    "just built",
    "just deployed",
    "just launched",
    "just solved",
    "just fixed",
    "finally",
    "milestone",
    "breakthrough",
    "successfully",
    "for the first time",
    "took me",
    "after weeks",
    "after days",
    "made a decision",
    "decided to",
    "going to start",
    "planning to",
]


EPISODE_PROMPT = """
Write a short episodic memory (2-3 sentences) summarising what happened in this interaction.

Write in third person. Focus on what the user did, decided, or learned.
Do not use "I", "me", "we", or "assistant".
Be specific and factual.

User said: {user_input}
"""


def _is_milestone(text: str) -> bool:
    """
    Returns True if the message looks like a significant event or milestone.
    Uses fast keyword matching — no LLM call needed for classification.
    """
    lowered = text.lower()
    return any(signal in lowered for signal in _MILESTONE_SIGNALS)


class EpisodicMemoryService:

    def __init__(self, collection, embedding_model, llm_service):
        self.collection = collection
        self.embedding_model = embedding_model
        self.llm_service = llm_service

    def process(self, user_input: str, assistant_reply: str, user_id: str):

        if not _is_milestone(user_input):
            return None

        logger.info(
            "Episodic: milestone detected, storing for user=%s | %r",
            user_id,
            user_input[:80],
        )

        # Generate a summary using the LLM — this is a generation task
        # (not classification) so even a 1B model handles it well
        try:
            episode_prompt = EPISODE_PROMPT.format(user_input=user_input)
            episode_summary = self.llm_service.generate(
                [{"role": "system", "content": episode_prompt}]
            ).strip()
        except Exception:
            # If LLM fails, store the raw user input as the episode
            logger.warning(
                "Episodic: LLM summary failed, storing raw input for user=%s",
                user_id,
            )
            episode_summary = user_input

        similar = find_similar_memory(
            self.collection,
            self.embedding_model,
            episode_summary,
            user_id=user_id,
            threshold=MEMORY_SIMILARITY_THRESHOLD,
        )

        if similar:
            return {
                "stored": False,
                "duplicate": True,
                "episode": similar["document"],
            }

        episode_id = str(uuid.uuid4())
        now = time.time()

        self.collection.add(
            ids=[episode_id],
            documents=[episode_summary],
            metadatas=[{
                "user_id": user_id,
                "source": "conversation",
                "created_at": now,
                "last_accessed": now,
                "access_count": 0,
                "importance": 0.7,
            }],
        )

        logger.info("Episodic: stored episode=%s for user=%s", episode_id, user_id)

        return {
            "stored": True,
            "duplicate": False,
            "id": episode_id,
            "episode": episode_summary,
        }
